### ISSUE TITLE
导入如何支持判断当前sheet

### ISSUE THREAD

**Issue by jzhy411423** [liuhuagui/gridexcel#1]
sheet1和sheet2数据不同，如何支持分sheet判断导入？

**Comment by liuhuagui** [comment]
你是想通过sheetName指定导入某个sheet，而不是所有sheet是吗

**Comment by liuhuagui** [comment]
还是同一个Excel文件，不同Sheet使用不同的解析方式

**Comment by jzhy411423** [comment]
同一个Excel，不同sheet列数据不同，比如第一个sheet10列对应一个对象，第二个sheet5列，对应另一个对象

**Comment by liuhuagui** [comment]
目前没有支持，实现思路是：
- 将原本Model中的消费函数
```java
protected Consumer<List<String>> readConsumer;
```
替换成一个HashMap<String,Consumer<List<String>>>
```java
protected HashMap<String,Consumer<List<String>>> readConsumersMap;
```
读Excel时，根据`SheetId`或者`SheetName`来选择相应的消费函数去处理对应的Sheet。
- 随后会进行支持，不过也欢迎进行PR。

**Comment by liuhuagui** [comment]
也可以通过复写Model中的处理方法，做快速实现。

**Comment by liuhuagui** [comment]
另外一种实现方式，我认为是你们想要的，将消费函数，使用`二元函数接口`实现：
```
protected BiConsumer<String,List<String>> readConsumer;
```
其中第一个参数传入SheetName，然后由用户自己来判断，选择解析方式。

**Comment by jzhy411423** [comment]
感谢，刚开始看函数式编程，学习研究中

**Comment by liuhuagui** [comment]
最近工作比较忙，但是我会尽快支持实现的，加油，你会深深的爱上函数式编程的，它太美了！

**Comment by jzhy411423** [comment]
感谢，已经使用二元函数调整，使用sheet名来进行不同的业务处理

**Comment by MrChencj** [comment]
> 目前没有支持，实现思路是：
> 
> * 将原本Model中的消费函数
> 
> ```java
> 受保护的 消费< 列表< 字符串 > > readConsumer;
> ```
> 
> 替换成一个HashMap <String，Consumer <List >>
> 
> ```java
> 保护 的HashMap < 字符串，消费者< 列表< 字符串 > > > readConsumersMap;
> ```
> 
> 读Excel中时，根据`SheetId`或者`SheetName`来选择相应的消费函数去处理对应的表。
> 
> * 随后会进行支持，不过也欢迎进行PR。

请问现在支持了吗
