### ISSUE TITLE
GridExcel.readByEventModel遇到的疑问

### ISSUE THREAD

**Issue by rainsmith** [liuhuagui/gridexcel#2]
你好，我有个产品excel中有504103行数据，使用GridExcel.readByEventModel读取excel的时候，设置windowSize=100，读取完之后我的List集合只有504100条数据，少了3条数据。但是设置windowSize=1的时候是正常的。引用代码如下：
List<ProductDTO> list = new ArrayList<>();
        GridExcel.readByEventModel(ins, ProductDTO.class, ExcelType.XLSX)
                .window(100, list::addAll)
                .process(cs ->{
                    ProductDTO dto = new ProductDTO();
                    dto.setCompanyId(cs.get(0));
                    dto.setProductName(cs.get(1));
                    dto.setProductNo(cs.get(2));
                    dto.setBasePrice(new BigDecimal(cs.get(4)));
                    return dto;
                },1);
System.out.println(list.size());
望解答，谢谢！

**Comment by liuhuagui** [comment]
您好，可以通过#get()方法取得剩余数据。
当启用监听函数，且<code>总数据 % windowSize != 0</code>,可以通过该方法获取剩余数据。

**Comment by liuhuagui** [comment]
多谢您的支持

**Comment by rainsmith** [comment]
试了一下确实解决了，感谢

**Comment by liuhuagui** [comment]
多谢您的支持，我们将会在新版本中对此进行优化。介意关闭issue吗

**Comment by rainsmith** [comment]
好咧

**Comment by easykoala** [comment]
我的sheet1一共5条数据， 其他2个sheet没有数据，输出只看到第1，3，5数据，2和4没有输出，谢谢！

        GridExcel.readByEventModel(resourceAsStream,Product.class, ExcelType.XLSX)
                .window(2,ts ->
                {
                    try{
                        System.out.println("sheet" + mapper.writeValueAsString(ts));
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                })//推荐在这里执行自己的业务逻辑
                .process(cs ->{
                    Product product = new Product();
                    product.setProductName(cs.get(0));
                    return product;
                },1).get();
