### ISSUE TITLE
gridexcel能返回表头信息吗

### ISSUE THREAD

**Issue by rainsmith** [liuhuagui/gridexcel#3]
你好，我想在分批读取数据的同时也把表头信息返回到。
因为我要读取的excel列数可能不固定，所以我需要读取表头的列有多少，按照工具提供的方法我找了一下貌似不可以？如果按照第一行开始取数据的话又无法按设定的数值来分批次读取，请问有什么建议吗

**Comment by liuhuagui** [comment]
表头信息如果与数据数据结构一致，让<code>startNum =1</code>即可，如果不一致可以同时使用计数器，在`readFunction函数`分类处理，或者统一使用`Map作为class`，可参照https://github.com/liuhuagui/gridexcel#%E6%97%A0%E5%AE%9E%E4%BD%93%E7%B1%BB%E8%AF%BB%E5%86%99Excel

**Comment by rainsmith** [comment]
太感谢了

**Comment by rainsmith** [comment]
很抱歉又来打扰了，readFunction函数返回的每行的cell值集合List<String>,如果excel中有某个cell没有数据，那一行的List<String>就少了一个，比如cs.get(10)，如果中间有一两个cell无数据，就产生了数组越界的异常，这个怎么解决。。

**Comment by rainsmith** [comment]
把eventModel改成userModel吗

**Comment by rainsmith** [comment]
现在就是数据量比较大，看说明用userModel怕会内存溢出

**Comment by liuhuagui** [comment]
cell Index based 0，且cell list 的长度应该是最大列数，程序中已经做了处理，您方便打印每行`list.size()`给我看一下吗

**Comment by rainsmith** [comment]
10
7
5
5
4
第一行是表头，有10列

**Comment by rainsmith** [comment]
<img width="571" alt="微信截图_20191019100518" src="https://user-images.githubusercontent.com/15644008/67136368-e5069080-f257-11e9-8232-fb2158e9af50.png">
图片能看到么

**Comment by liuhuagui** [comment]
大概明白了，如果中间缺失，应该不会影响cell list的长度的吧

**Comment by rainsmith** [comment]
会影响取数据呀，比如我想取第3行第7列的数据，用的是cs.get(6)来获取，但是第3行返回的长度是5，这时候用cs.get(6)就会报错了

**Comment by liuhuagui** [comment]
理解，这个在函数接口中判断处理即可，使用时间复杂度置换空间复杂度。想象一下，你要读100万行数据，结果只有某一行的列数为100，其他为80，你是选择持有100万个`list.size()==80`的list，还是持有100万个`list.size()==100`？尽管使用了窗口控制，但是会促使GC更频繁。中间缺失不会造成index的顺序混乱就应该是正常的。

**Comment by liuhuagui** [comment]
您有什么好的主意吗

**Comment by rainsmith** [comment]
但是现在像我这种情况，不就是造成index的顺序混乱吗，本来应该get()到的值却get不到，因为我根本不知道这个excel表当中会有哪一列出现空数据。导致本来用cs.get(1)应该得到“养车A座椅”的值，现在因为第1列为空，我现在用get(1)得到的是“AB263952"，这就乱了。

**Comment by rainsmith** [comment]
应该只能用UserModel这个方法了，我试了一下这个方法可以

**Comment by rainsmith** [comment]
我提个小主意，因为您返回的是List<String>，所以中间缺失的数据最好还是用空字符串体现出来好一点吧，起码取数据不会有错位的问题。您这里考虑到了空间复杂度的问题，但是你用了分批处理的技术，我想使用者应该也不会一次读100w的数据吧，这点应该可以忽略。或者您考虑一下再重载一个方法，让调用者选择是否忽略空单元格的问题。在此期待GridExcel越来越完善，谢谢你的解答

**Comment by liuhuagui** [comment]
不好意思，我测了一下，确实没有实现程序预期的效果，出现了Bug，多谢您的支持，会尽快修复该问题！

**Comment by liuhuagui** [comment]
不好意思，我测了一下，确实没有实现程序预期的效果，出现了Bug，多谢您的支持，会尽快修复该问题！

**Comment by rainsmith** [comment]
精益求精，很期待，主要我觉得这工具确实很快

**Comment by liuhuagui** [comment]
提供一个快速解决办法：把您的xlsx文件使用Excel打开另存为xls文件，xlsEventModel可以正常工作

**Comment by rainsmith** [comment]
谢谢，xls试了确实可以。不过我们正式的生产系统要用xlsx，xls只能存65535不够用

**Comment by rainsmith** [comment]
还有，如果发新版本了，请问会有通知吗，虽然关注了但是不知道你们会有通知消息吗
