### ISSUE TITLE
抱歉，好像还有个小问题

### ISSUE THREAD

**Issue by rainsmith** [liuhuagui/gridexcel#4]
<img width="280" alt="微信截图_20191019114608" src="https://user-images.githubusercontent.com/15644008/67137351-2d2caf80-f266-11e9-9e21-8f4c27df97e6.png">
<img width="303" alt="微信截图_20191019114712" src="https://user-images.githubusercontent.com/15644008/67137352-2d2caf80-f266-11e9-809c-2e79810b1510.png">

**Comment by rainsmith** [comment]
第一行10条数据，用cs.get(7)没问题
第二行7条数据，用cs.get(7)又抛错误了，后面3条没有数据也没有用”“表示
不过这个我通过程序判断应该也可以控制

**Comment by 617450941** [comment]
这样判断 最终的结果是不准确的 这个数据程序的大bug  这样导致这个库是无法正常使用的

**Comment by liuhuagui** [comment]
@617450941 不好意思，一直在解决[smalldoc](https://github.com/liuhuagui/smalldoc)的问题，这两天会对GridExcel进行修改，发布新版本，多谢支持🙏

**Comment by 617450941** [comment]
@rainsmith  项目上线了 才发现这个问题 没用空字符填充空的单元数据 导致下面全部列的数据都是错的

**Comment by rainsmith** [comment]
期待新版本中修复

**Comment by liuhuagui** [comment]
> 这样判断 最终的结果是不准确的 这个数据程序的大bug 这样导致这个库是无法正常使用的

@617450941 像 @rainsmith 那样，你可以先使用XlsEventModel来解决，末尾出现的缺失可以通过程序来判断，这和POI提供的UserModel是相同的，我会尝试思考更合适的解决方法。

**Comment by liuhuagui** [comment]
新版本已经发布 @rainsmith @617450941 ，https://github.com/liuhuagui/gridexcel/releases

**Comment by rainsmith** [comment]
好的
