### ISSUE TITLE
excel有的空格无法识别到

### ISSUE THREAD

**Issue by glacier0622** [liuhuagui/gridexcel#6]
我有个excel模板，里面有空格
 但是有的空格无法识别，有的空格又能识别，请问下是什么原因额  
我可以把模板excel发给您看看

[20200327071.xlsx](https://github.com/liuhuagui/gridexcel/files/4393890/20200327071.xlsx)
第2-5列，只能识别到2个空行出来。  不知道是什么原因
望回答，谢谢

**Comment by liuhuagui** [comment]
应该是单元格内容格式的问题吧，可以试着清除下格式

**Comment by glacier0622** [comment]
> 应该是单元格内容格式的问题吧，可以试着清除下格式

尝试清除了格式。但是还是无法识别。。

**Comment by liuhuagui** [comment]
建议先使用原生的POI API做测试，定位问题

**Comment by glacier0622** [comment]
> 建议先使用原生的POI API做测试，定位问题

你好，用原生poi api测试过了，没有问题。。所有单元格都能获取到。
     process方法获取到cs时候，有些无数据单元格无法识别（比如4个无数据单元格只识别到2个），导致cs.get错位

**Comment by liuhuagui** [comment]
请给出使用版本

**Comment by glacier0622** [comment]
> 请给出使用版本

		<dependency>
			<groupId>com.github.liuhuagui</groupId>
			<artifactId>gridexcel</artifactId>
			<version>2.2</version>
		</dependency>

**Comment by liuhuagui** [comment]
#3，#5，2.3 版本已经解决该问题，[更新日志](https://github.com/liuhuagui/gridexcel/releases)

**Comment by glacier0622** [comment]
> #3，#5，https://github.com/liuhuagui/gridexcel/releases

sorry，我试一下。。

**Comment by liuhuagui** [comment]
如果解决了你的问题，欢迎star与分享，多谢您的支持！
