### ISSUE TITLE
为何数据行跳着读取？

### ISSUE THREAD

**Issue by easykoala** [liuhuagui/gridexcel#7]
我的sheet1一共5条数据， 其他2个sheet没有数据，输出只看到第1，3，5数据，2和4没有输出。不知为何，谢谢！

    GridExcel.readByEventModel(resourceAsStream,Product.class, ExcelType.XLSX)
            .window(2,ts ->
            {
                try{
                    System.out.println("sheet" + mapper.writeValueAsString(ts));
                } catch (Exception e) {
                    e.printStackTrace();
                }
            })//推荐在这里执行自己的业务逻辑
            .process(cs ->{
                Product product = new Product();
                product.setProductName(cs.get(0));
                return product;
            },1).get();

**Comment by liuhuagui** [comment]
请给出测试结果与测试文件截图，以及依赖版本

**Comment by easykoala** [comment]
System.out.println("sheet" + mapper.writeValueAsString(ts));
这里输出的应该是相当于分页处理，ts这个取第一条？这个变量也许用处不大，
用list收集正常

**Comment by easykoala** [comment]
应该是对的， ts 变量是 Consumer<List<T>>已经收集好了，
是我输出的时候的问题，信息太长没有注意看，抱歉:)
