### ISSUE TITLE
能否在标题栏下面定义字段名称，自动匹配？

### ISSUE THREAD

**Issue by easykoala** [liuhuagui/gridexcel#8]
能否在标题栏下面定义一栏字段名称，然后自动匹配bean的字段？

**Comment by liuhuagui** [comment]
这与GridExcel的实现思想是一致的。但是定义在Excel中不如像GridExcel一样定义在程序中，而且定义在Excel中是无法解析复杂对象的。如果对您有帮助，欢迎star与分享。
