### ISSUE TITLE
能否跳出循环？

### ISSUE THREAD

**Issue by easykoala** [liuhuagui/gridexcel#9]
先检查数据，如果有问题能否马上跳出循环？
另外能否取得当前行号？

**Comment by liuhuagui** [comment]
这些都是你在process函数中自己可以实现的逻辑！

**Comment by easykoala** [comment]
process函数里面设个变量，return null，但process函数还是不断循环？如何解决？
当前行号要自己计数吗？

**Comment by liuhuagui** [comment]
比如抛出个异常试试

**Comment by liuhuagui** [comment]
当前行号，暂时只能自己计数了，因为一直没有碰到过这种需求，一般数据都有对应的ID，如果呼声强烈，可能在下一个版本增加作为process函数的第二参数！

**Comment by easykoala** [comment]
谢谢，明天再试试
